spring.application.name=module5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=jdbc:mysql://localhost:3306/fullstack?useSSL=false
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
employeeService.base.url=http://localhost:8080/

weather.api.base.url=http://api.weatherapi.com/v1/
weather.api.key=281af37323974fa98cd163210262806

management.endpoints.web.exposure.include=*

spring.security.user.name=Akhilesh
spring.security.user.password=pass123
